---
 
 - name: Remove swapfile from /etc/fstab
   mount:
     name: swap
     fstype: swap
     state: absent
 - name: turn off swap
   command: swapoff -a
 - name: Disable SELinux
   selinux:
     state: disabled
 - name: Ensure SELinux is set to enforcing mode
   lineinfile:
     path: /etc/selinux/config
     regexp: '^SELINUX='
     line: SELINUX=disabled
 - name: Enable Kernel module br_netfilter
   modprobe:
     name: br_netfilter
     state: present
     
 - name: Enable bridgeNF for IPTables
   shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"
   ignore_errors: yes
 - name: enable iptables for Kubernetes
   blockinfile:
     path: /etc/sysctl.d/k8s.conf
     block: |
       net.bridge.bridge-nf-call-ip6tables = 1
       net.bridge.bridge-nf-call-iptables = 1
     create: yes
     state: present
 - name: Disable Firewalld service
   systemd:
     name: firewalld
     state: stopped
     masked: yes
     enabled: no